import type { Metadata } from "next";
import TopBar from "./components/MainNavBar";
import { Providers } from "./Providers";
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <Providers>
          <div className="dark">
            <TopBar />
            <main>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
