name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
            
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install

      - name: Cache build files
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: build-cache-${{ github.ref }}-${{ hashFiles('package.json', 'pnpm-lock.yaml') }}
          restore-keys: |
            build-cache-${{ github.ref }}-
            build-cache-

      - name: Build
        run: pnpm run build

      - name: Install firebase-tools
        run: pnpm add -g firebase-tools

      - name: Add pnpm global bin to PATH
        run: echo "${{ runner.tool_cache }}/pnpm/global/5/node_modules/.bin" >> $GITHUB_PATH

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONAL_WEBSITE_7B03D }}
          channelId: live
          projectId: personal-website-7b03d
